### ISSUE TITLE
specify listen address

### ISSUE THREAD

**Issue by patrickpierson** [mblayman/httpony#7]
I figure this would be an enhancement.  I am happy to have a crack at it.  The listen address should be able to be specified (at least 0.0.0.0/listen to everything).  Ran into issue today where I wanted to use httpony to watch for requests however it is hard-coded to only listen on localhost.

**Comment by mblayman** [comment]
That sounds like a great addition. Can I request that you use argparse if you choose to take this on? You can check out [handroll](https://github.com/handroll/handroll) if you want an example.

I was thinking `--hostname` would be a good option name, but the short flag version would be `-h` which conflicts with argparse's built-in help. Maybe `-l` / `--listen` is a good name. What do you think?

**Comment by patrickpierson** [comment]
definitely.  was going to copy what I did for https://github.com/patrickpierson/public_ip_change/blob/master/public_ip_change.py -l --listen sounds perfect.
